---

- name: Add puppet to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: 192.168.50.2\s+puppet
    line: "192.168.50.2    puppet"
  sudo: true

- name: Install vim
  apt: name=vim state=installed
  sudo: true

- name: Copy puppet.conf for agent
  copy: src=puppet.conf dest=/etc/puppet/puppet.conf
  sudo: true
